# Generated by Django 4.2.2 on 2023-06-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='cedula',
            new_name='rut',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='ciudad',
            field=models.CharField(blank=True, default='Desconocido', max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='comuna',
            field=models.CharField(blank=True, default='Desconocido', max_length=100, null=True, verbose_name='Comuna'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='diagnostico1',
            field=models.CharField(blank=True, default='Desconocido', max_length=100, null=True, verbose_name='Diagnostico1'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='diagnostico2',
            field=models.CharField(blank=True, default='Desconocido', max_length=100, null=True, verbose_name='Diagnostico2'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='diagnostico3',
            field=models.CharField(blank=True, default='Desconocido', max_length=100, null=True, verbose_name='Diagnostico3'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='edad',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='enfermedad_cronica',
            field=models.CharField(blank=True, default='Desconocido', max_length=100, null=True, verbose_name='Enfermedad_cronica'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='enfermedad_padece',
            field=models.CharField(blank=True, default='Desconocido', max_length=100, null=True, verbose_name='Enfermedad_padece'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='peso',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='region',
            field=models.CharField(blank=True, default='Desconocido', max_length=100, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nacionalidad',
            field=models.CharField(blank=True, choices=[('venezolano', 'Venezolano'), ('chileno', 'Chileno')], default='chileno', max_length=150, null=True, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.CharField(blank=True, choices=[('master', 'Master'), ('usuario', 'Usuario'), ('profesional', 'Profesional'), ('paciente', 'Paciente')], default='usuario', max_length=150, null=True, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='telefono',
            field=models.CharField(blank=True, default='00000000000', max_length=50, null=True, verbose_name='Telefono'),
        ),
    ]
